//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tinder4Jobs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkedinCompany
    {
        public LinkedinCompany()
        {
            this.LinkedinJob = new HashSet<LinkedinJob>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string CompanyId { get; set; }
    
        public virtual ICollection<LinkedinJob> LinkedinJob { get; set; }
    }
}
